# -*- coding: utf-8 -*-
"""
Created on Fri Mar 13 14:26:15 2015

@author: Daniele
"""

# Each new term in the Fibonacci sequence is generated by adding the previous
# two terms. By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed
# four million, find the sum of the even-valued terms.

def fib(n):
    a, b = 0, 1
    for i in range(0, n):
        a, b = b, a + b
    return a

fib_seq = []

i = 0
while fib(i) < 4000000:
    fib_seq.append(fib(i))
    i += 1
      
print sum([i for i in fib_seq if i % 2 == 0])