# -*- coding: utf-8 -*-
"""
Created on Thu Mar 19 09:33:31 2015

@author: Daniele
"""

#Triangle, pentagonal, and hexagonal numbers are generated by the following
#formulae:
#
#Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
#Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
#Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
#It can be verified that T285 = P165 = H143 = 40755.
#
#Find the next triangle number that is also pentagonal and hexagonal.

import time
from Euler import *

n = 286
Tn = triangle(n)

start = time.time()

while all((is_penta(Tn), is_hexa(Tn))) == False:
    n += 1
    Tn = triangle(n)
    
elapsed = (time.time() - start)
print Tn, 'in %5.3f seconds' % elapsed