# -*- coding: utf-8 -*-
"""
Created on Thu Mar 19 08:38:08 2015

@author: Daniele
"""

#Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten
#pentagonal numbers are:
#
#1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
#
#It can be seen that P4 + P7 = 22 + 70 = 92 = P8.
#However, their difference, 70 − 22 = 48, is not pentagonal.
#
#Find the pair of pentagonal numbers, Pj and Pk, for which their sum and
#difference are pentagonal and D = |Pk − Pj| is minimised.
#What is the value of D?
#
#From the definition of Pn, it is easy to obtain that Pn is pentagonal if
#
# n = (1 + sqrt(24*Pn + 1)) / 6
#
#is a natural number.
#
#One option is to create a big list of Pentagonals and check pairs for the
#solution.

import time
from Euler import *
    
pentas = penta_list(2500)   #through trials
sols = []

start = time.time()

for p1 in pentas:
    for p2 in filter(lambda x: x < p1, pentas):
        s = p1 + p2
        d = p1 - p2
        if is_penta(s) and is_penta(d):
            sols.append((p1, p2, s, d))
            
elapsed = (time.time() - start)
print sols, 'in %5.3f seconds' % elapsed